#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${INGEST_USER}') THEN
    CREATE ROLE ${INGEST_USER} LOGIN PASSWORD '${INGEST_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${DBT_USER}') THEN
    CREATE ROLE ${DBT_USER} LOGIN PASSWORD '${DBT_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${BI_READER_USER}') THEN
    CREATE ROLE ${BI_READER_USER} LOGIN PASSWORD '${BI_READER_PASSWORD}';
  END IF;
END
\$\$;

CREATE SCHEMA IF NOT EXISTS raw AUTHORIZATION ${INGEST_USER};
CREATE SCHEMA IF NOT EXISTS audit AUTHORIZATION ${INGEST_USER};
CREATE SCHEMA IF NOT EXISTS staging AUTHORIZATION ${DBT_USER};
CREATE SCHEMA IF NOT EXISTS marts AUTHORIZATION ${DBT_USER};

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${INGEST_USER}, ${DBT_USER}, ${BI_READER_USER};
GRANT USAGE ON SCHEMA raw TO ${DBT_USER};
GRANT USAGE ON SCHEMA marts TO ${BI_READER_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA raw TO ${DBT_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA marts TO ${BI_READER_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${INGEST_USER} IN SCHEMA raw GRANT SELECT ON TABLES TO ${DBT_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${DBT_USER} IN SCHEMA marts GRANT SELECT ON TABLES TO ${BI_READER_USER};
SQL
